theme = "onedark-he"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # show hidden files

[editor.indent-guides]
render = true
